# Optional: GitHub Actions for automated deployment
name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@v1
      with:
        app_name: odoo-experten-dev-preview
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}